export const FETCH_USERS = "FETCH_USERS";
export const USERS_RECIEVE = "USERS_RECIEVE";

export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const USER_DETAILS_RECIEVE = "USER_DETAILS_RECIEVE";
